<?php
/**
 * Created by PhpStorm.
 * User: Utilisateur
 * Date: 10/03/2017
 * Time: 16:48
 */

namespace AppBundle\Repository;

use AppBundle\Entity\Favourite;
use AppBundle\Entity\User;

/**
 * FavouriteRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavouriteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param User $user
     * @return array
     */
    public function getFavouritesTweetByUser(User $user)
    {
        return $this->createQueryBuilder('f')
            ->select('f')
            ->andWhere('f.user = :id')
            ->setParameter('id', $user->getId())
            ->getQuery()
            ->getResult();
    }
    public function getFavourite($favouriteId,$userId)
    {
        return $this->createQueryBuilder('f')
            ->select('f')
            ->andWhere('f.id = :favouriteId')
            ->andWhere('f.user = :userId')
            ->setParameter('favouriteId', $favouriteId)
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}